# Generated by Django 5.2.6 on 2026-01-17 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_product'),
        ('products', '0005_color_remove_product_attribute_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant', verbose_name='product'),
        ),
    ]
