# Generated by Django 5.2.6 on 2026-01-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(height_field='2880', upload_to='core/banner', verbose_name='Banner', width_field='600')),
            ],
        ),
    ]
