# Generated by Django 5.2.6 on 2026-01-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='HomePageModel',
        ),
    ]
