# Generated by Django 5.2.6 on 2026-01-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_homepage_homepagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagemodel',
            name='banner',
            field=models.ImageField(upload_to='core/banner', verbose_name='Banner'),
        ),
    ]
