# Generated by Django 5.2.6 on 2025-12-25 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Coupon Code')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Discount Value')),
                ('discount_type', models.CharField(choices=[('v', 'Fixed Amount'), ('p', 'Percentage')], max_length=1, verbose_name='Discount Type')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Available Quantity')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Used Count')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid To')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid?')),
                ('status', models.CharField(choices=[('p', 'Pending'), ('c', 'Confirmed'), ('s', 'Sent'), ('f', 'Finished')], default='p', max_length=1, verbose_name='Status')),
                ('province', models.CharField(max_length=50, verbose_name='province')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('full_address', models.CharField(max_length=255, verbose_name='full address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('shipping_method', models.CharField(choices=[('post', 'Post'), ('tipax', 'Tipax')], default='post', max_length=10, verbose_name='shipping method')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address', verbose_name='address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='price (Toman)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
