# Generated by Django 5.2.6 on 2025-11-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Coupon Code')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Discount Value (Toman)')),
                ('discount_type', models.CharField(choices=[('v', 'Fixed Amount'), ('p', 'Percentage')], max_length=1, verbose_name='Discount Type')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Available Quantity')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Used Count')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid To')),
            ],
        ),
    ]
