# Generated by Django 5.2.6 on 2026-01-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Confirmed'), ('s', 'Sent'), ('f', 'Finished'), ('failed', 'Failed')], default='p', max_length=6, verbose_name='Status'),
        ),
    ]
