# Generated by Django 5.2.6 on 2025-11-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('post', 'Post'), ('tipax', 'Tipax')], default='post', max_length=10, verbose_name='shipping method'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Discount Value'),
        ),
    ]
