# Generated by Django 5.2.6 on 2025-12-25 15:27

import django.core.validators
import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'attribute category',
                'verbose_name_plural': 'attribute categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='brand')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='brand code')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='attribute name')),
                ('is_variant_defining', models.BooleanField(default=False, verbose_name='Is this a variant-defining attribute?')),
                ('show_in_specifications', models.BooleanField(default=True, verbose_name='Show in specifications in detail page?')),
                ('allow_multiple_values', models.BooleanField(default=False, verbose_name='امکان انتخاب چند مقدار همزمان در واریانت')),
                ('attribute_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='products.attributecategory', verbose_name='attribute category')),
            ],
            options={
                'verbose_name': 'attribute',
                'verbose_name_plural': 'attributes',
                'ordering': ['attribute_category'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='attribute value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute', verbose_name='attribute')),
            ],
            options={
                'verbose_name': 'attribute value',
                'verbose_name_plural': 'attribute values',
                'ordering': ['attribute__id'],
                'unique_together': {('value', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ParentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='parent product name')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='last modified date')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_parents', to='products.brand', verbose_name='brand')),
                ('specification_values', models.ManyToManyField(blank=True, limit_choices_to={'attribute__is_variant_defining': False, 'attribute__show_in_specifications': True}, related_name='parent_products', to='products.attributevalue', verbose_name='shared specifications')),
            ],
            options={
                'verbose_name': 'parent product',
                'verbose_name_plural': 'parent products',
                'ordering': ['category', 'brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='comment content')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('is_recommend', models.BooleanField(blank=True, default=None, null=True, verbose_name='   ')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is approved by admin?')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='last modified date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.parentproduct', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_full_name', models.CharField(blank=True, max_length=500, verbose_name='Full Name (Cached)')),
                ('initial_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='price (Toman)')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], default='amount', max_length=50, verbose_name='discount type')),
                ('discount_value', models.PositiveIntegerField(default=0, verbose_name='discount value')),
                ('final_price', models.DecimalField(decimal_places=0, max_digits=11, null=True, verbose_name='final price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('is_amazing', models.BooleanField(default=False, verbose_name='is amazing?')),
                ('is_best_selling', models.BooleanField(default=False, verbose_name='is best selling?')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='last modified date')),
                ('attribute_values', models.ManyToManyField(limit_choices_to={'attribute__is_variant_defining': True}, to='products.attributevalue', verbose_name='attribute values')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.parentproduct', verbose_name='product name')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='category code')),
                ('attribute_categories', models.ManyToManyField(blank=True, to='products.attributecategory', verbose_name='attribute categories')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_parents', to='products.productcategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(related_name='brands', to='products.productcategory', verbose_name='related categories'),
        ),
        migrations.CreateModel(
            name='AttributeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_feature', models.BooleanField(default=False, verbose_name='Show in product tite?')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute', verbose_name='attribute')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Attribute Rule',
                'verbose_name_plural': 'Attribute Rules',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='product_category',
            field=models.ManyToManyField(related_name='attributes', through='products.AttributeRule', to='products.productcategory', verbose_name='related categories'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.product_image_upload_to, verbose_name='product image')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt text')),
                ('is_main_image', models.BooleanField(default=False, verbose_name='is main image?')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.parentproduct', verbose_name='parent product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
            },
        ),
        migrations.AddConstraint(
            model_name='attributerule',
            constraint=models.UniqueConstraint(fields=('attribute', 'category', 'brand'), name='unique_attribute_category_brand'),
        ),
        migrations.AddConstraint(
            model_name='attributerule',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', True)), fields=('attribute', 'category'), name='unique_attribute_category_when_brand_is_null'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_image', True)), fields=('parent_product',), name='unique_main_image_per_product'),
        ),
    ]
