# Generated by Django 5.2.6 on 2025-09-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_amazing',
            field=models.BooleanField(default=False, verbose_name='محصول شگفت\u200cانگیز؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='موجود است؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_selling',
            field=models.BooleanField(default=False, verbose_name='پرفروش است؟'),
        ),
    ]
