# Generated by Django 5.2.6 on 2026-01-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_comments_is_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='code',
            field=models.CharField(default=1, max_length=20, verbose_name='code for lookup (DO NOT CHANGE THE VALUE!)'),
            preserve_default=False,
        ),
    ]
