# Generated by Django 5.2.6 on 2026-01-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_attribute_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_attribute',
            field=models.ManyToManyField(limit_choices_to={'attribute__code': 'color'}, related_name='product_colors', to='products.attributevalue', verbose_name='attribute values'),
        ),
    ]
