# Generated by Django 5.2.6 on 2026-01-17 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_color_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50, verbose_name='Color Name')),
                ('hex_code', models.CharField(max_length=50, unique=True, verbose_name='Hex Code')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='attribute_values',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_attribute',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent_product',
        ),
        migrations.RenameModel(
            old_name='ParentProduct',
            new_name='ProductParent',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_full_name', models.CharField(blank=True, max_length=500, verbose_name='Full Name (Cached)')),
                ('initial_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='price (Toman)')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], default='amount', max_length=50, verbose_name='discount type')),
                ('discount_value', models.PositiveIntegerField(default=0, verbose_name='discount value')),
                ('final_price', models.DecimalField(decimal_places=0, max_digits=11, null=True, verbose_name='final price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('is_amazing', models.BooleanField(default=False, verbose_name='is amazing?')),
                ('is_best_selling', models.BooleanField(default=False, verbose_name='is best selling?')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='last modified date')),
                ('attribute_values', models.ManyToManyField(limit_choices_to={'attribute__is_variant_defining': True}, to='products.attributevalue', verbose_name='attribute values')),
                ('color_attribute', models.ManyToManyField(limit_choices_to={'attribute__code': 'color'}, related_name='product_colors', to='products.attributevalue', verbose_name='color values')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productparent', verbose_name='product name')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color', verbose_name='Color')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Product Variant')),
            ],
        ),
    ]
