# Generated by Django 5.2.6 on 2025-09-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='تصویر شاخص؟'),
        ),
    ]
