# Generated by Django 5.2.6 on 2026-01-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_product'),
        ('orders', '0005_alter_orderitem_product'),
        ('products', '0005_color_remove_product_attribute_values_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
