# Generated by Django 5.2.6 on 2026-01-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color_attribute',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='initial_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
        migrations.AddField(
            model_name='products',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], default='amount', max_length=50, verbose_name='discount type'),
        ),
        migrations.AddField(
            model_name='products',
            name='discount_value',
            field=models.PositiveIntegerField(default=0, verbose_name='discount value'),
        ),
        migrations.AddField(
            model_name='products',
            name='final_price',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True, verbose_name='final price'),
        ),
        migrations.AddField(
            model_name='products',
            name='initial_price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='price (Toman)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Is Available?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock'),
        ),
    ]
