# Generated by Django 5.2.6 on 2025-09-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_attribute_options_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_variable',
        ),
    ]
