# Generated by Django 5.2.6 on 2026-01-17 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productvariant_color_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productvariant', verbose_name='Product Variant'),
        ),
    ]
