# Generated by Django 5.2.6 on 2026-01-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_product_variant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
