# Generated by Django 5.2.6 on 2026-01-17 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='products.productparent', verbose_name='product name'),
        ),
    ]
