# Generated by Django 5.2.6 on 2025-09-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_color_remove_product_fixed_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvalue',
            name='value',
            field=models.CharField(default=1, max_length=50, verbose_name='color value'),
            preserve_default=False,
        ),
    ]
