# Generated by Django 5.2.6 on 2025-09-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_colorvalue_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_attributes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='discounted price (Toman)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_amazing',
            field=models.BooleanField(default=False, verbose_name='is amazing?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is available'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_selling',
            field=models.BooleanField(default=False, verbose_name='is best selling?'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='price (Toman)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_attributes',
            field=models.ManyToManyField(to='products.attributevalue', verbose_name='variant attributes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='products.color', verbose_name='available colors'),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='brand')),
                ('categoty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='products.productcategory', verbose_name='category')),
            ],
        ),
        migrations.DeleteModel(
            name='ColorValue',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
