# Generated by Django 5.2.6 on 2025-09-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productvariant_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant_attributes',
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(to='products.attributevalue', verbose_name='attribute values'),
        ),
    ]
