# Generated by Django 5.2.6 on 2026-01-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productvariant_parent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_available',
            field=models.BooleanField(default=1, verbose_name='Is Available?'),
            preserve_default=False,
        ),
    ]
