# Generated by Django 5.2.6 on 2026-01-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productvariant_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='is_best_selling',
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(verbose_name='is available?'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_available',
            field=models.BooleanField(verbose_name='is available?'),
        ),
    ]
