# Generated by Django 5.2.6 on 2025-09-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_categoty_brand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='is_in_title',
            field=models.BooleanField(default=False, verbose_name='include in product title'),
        ),
    ]
