# Generated by Django 5.2.6 on 2026-09-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_productvariant_is_best_selling_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'product variant', 'verbose_name_plural': 'product variants'},
        ),
    ]
