# Generated by Django 5.2.6 on 2026-09-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productvariant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_key_feature',
            field=models.BooleanField(default=False, verbose_name='نمایش در ویژگی\u200cهای کلیدی بالای صفحه'),
        ),
    ]
