# Generated by Django 5.2.6 on 2025-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productcategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='category code'),
        ),
    ]
