# Generated by Django 5.2.6 on 2025-09-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productcategory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='code',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='brand code'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(related_name='brands', to='products.productcategory', verbose_name='related categories'),
        ),
    ]
