# Generated by Django 5.2.6 on 2025-10-01 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.CreateModel(
            name='AttributeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_feature', models.BooleanField(default=False, verbose_name='Show in product tite?')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute', verbose_name='attribute')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Attribute Rule',
                'verbose_name_plural': 'Attribute Rules',
                'unique_together': {('attribute', 'category', 'brand')},
            },
        ),
    ]
