# Generated by Django 5.2.6 on 2025-10-01 12:14

from django.db import migrations

def create_through_relations(apps, schema_editor):
    Attribute = apps.get_model('products', 'Attribute')
    AttributeRule = apps.get_model('products', 'AttributeRule')
    for attribute in Attribute.objects.all():
        for category in attribute.categories.all():
            AttributeRule.objects.create(
                attribute=attribute,
                category=category,
                brand=None,
                is_main_feature=False
            )

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_specifications_attributerule'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]