# Generated by Django 5.2.6 on 2025-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_attribute_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(related_name='attributes', through='products.AttributeRule', to='products.productcategory', verbose_name='related categories'),
        ),
    ]
