# Generated by Django 5.2.6 on 2025-10-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_attribute_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributerule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='parentproduct',
            name='slug',
        ),
        migrations.AddConstraint(
            model_name='attributerule',
            constraint=models.UniqueConstraint(fields=('attribute', 'category', 'brand'), name='unique_attribute_category_brand'),
        ),
        migrations.AddConstraint(
            model_name='attributerule',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', True)), fields=('attribute', 'category'), name='unique_attribute_category_when_brand_is_null'),
        ),
    ]
