# Generated by Django 5.2.6 on 2025-10-02 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_remove_attribute_attribute_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributecategory',
            options={'ordering': ['name'], 'verbose_name': 'attribute category', 'verbose_name_plural': 'attribute categories'},
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='categories',
            new_name='product_category',
        ),
        migrations.RemoveField(
            model_name='attributerule',
            name='attribute_group',
        ),
        migrations.AddField(
            model_name='attribute',
            name='attrobute_categoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='products.attributecategory', verbose_name='attribute category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='attribute_categories',
            field=models.ManyToManyField(blank=True, to='products.attributecategory', verbose_name='attribute categories'),
        ),
    ]
