# Generated by Django 5.2.6 on 2025-10-02 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_attributecategory_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attrobute_categoy',
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_categoy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='products.attributecategory', verbose_name='attribute category'),
        ),
    ]
