# Generated by Django 5.2.6 on 2025-10-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_attribute_attrobute_categoy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute_categoy',
            new_name='attribute_category',
        ),
    ]
