# Generated by Django 5.2.6 on 2025-10-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_rename_attribute_categoy_attribute_attribute_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['attribute_category'], 'verbose_name': 'attribute', 'verbose_name_plural': 'attributes'},
        ),
        migrations.AlterModelOptions(
            name='attributecategory',
            options={'ordering': ['id'], 'verbose_name': 'attribute category', 'verbose_name_plural': 'attribute categories'},
        ),
    ]
