# Generated by Django 5.2.6 on 2025-10-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='product',
        ),
        migrations.AddField(
            model_name='comments',
            name='parent_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.parentproduct', verbose_name='product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='is_recommend',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='recommends product?'),
        ),
    ]
