# Generated by Django 5.2.6 on 2025-10-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_attributecategory_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_variant_defining',
            field=models.BooleanField(default=False, verbose_name='Is this a variant-defining attribute?'),
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='specification_values',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute__is_variant_defining': False}, related_name='parent_products', to='products.attributevalue', verbose_name='shared specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(limit_choices_to={'attribute__is_variant_defining': True}, to='products.attributevalue', verbose_name='attribute values'),
        ),
    ]
