# Generated by Django 5.2.6 on 2025-10-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_attribute_is_variant_defining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='show_in_specifications',
            field=models.BooleanField(default=True, verbose_name='Show in specifications in detail page?'),
        ),
    ]
