# Generated by Django 5.2.6 on 2025-11-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_product__full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main_image',
            field=models.BooleanField(default=False, verbose_name='is main image?'),
        ),
        migrations.AlterField(
            model_name='attributecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='is_recommend',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='   '),
        ),
    ]
