# Generated by Django 5.2.6 on 2025-11-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_productimage_is_main_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'product image', 'verbose_name_plural': 'product images'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='specification_values',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute__is_variant_defining': False, 'attribute__show_in_specifications': True}, related_name='parent_products', to='products.attributevalue', verbose_name='shared specifications'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_image', True)), fields=('parent_product',), name='unique_main_image_per_product'),
        ),
    ]
