# Generated by Django 5.2.6 on 2025-11-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_parentproduct_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='initial_price',
        ),
    ]
