# Generated by Django 5.2.6 on 2025-09-27 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_amazing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_best_selling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_variable',
            field=models.BooleanField(default=False, verbose_name='آیا محصول متغیر است؟'),
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام ویژگی')),
                ('categories', models.ManyToManyField(related_name='attributes', to='products.productcategory', verbose_name='دسته\u200cبندی\u200cهای مرتبط')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار ویژگی')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی محصول',
                'verbose_name_plural': 'مقادیر ویژگی\u200cهای محصولات',
                'ordering': ['attribute'],
                'unique_together': {('value', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fixed_attribute',
            field=models.ManyToManyField(blank=True, to='products.attributevalue', verbose_name='ویژگی\u200cهای ثابت'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت با تخفیف (تومان)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود است؟')),
                ('is_amazing', models.BooleanField(default=False, verbose_name='محصول شگفت\u200cانگیز؟')),
                ('is_best_selling', models.BooleanField(default=False, verbose_name='پرفروش است؟')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='محصول')),
                ('variant_attributes', models.ManyToManyField(to='products.attributevalue', verbose_name='ویژگی\u200cهای این نسخه')),
            ],
            options={
                'verbose_name': 'واریانت محصول',
                'verbose_name_plural': 'واریانت\u200cهای محصولات',
            },
        ),
    ]
