# Generated by Django 5.2.6 on 2025-09-27 08:42

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['name'], 'verbose_name': 'attribute', 'verbose_name_plural': 'attributes'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ['attribute'], 'verbose_name': 'attribute value', 'verbose_name_plural': 'attribute values'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'product category', 'verbose_name_plural': 'product categories'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-id'], 'verbose_name': 'product image', 'verbose_name_plural': 'product images'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'product variant', 'verbose_name_plural': 'product variants'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.product', verbose_name='parent product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PARENT', 'parent'), ('CHILD', 'child')], default='CHILD', max_length=10, verbose_name='product type'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(related_name='attributes', to='products.productcategory', verbose_name='related categories'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=255, verbose_name='attribute name'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute', verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=255, verbose_name='attribute value'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fixed_attribute',
            field=models.ManyToManyField(blank=True, to='products.attributevalue', verbose_name='fixed attributes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_variable',
            field=models.BooleanField(default=False, verbose_name='product has color?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory', verbose_name='parent category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt text'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.product_image_upload_to, verbose_name='product image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified date'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='discounted price (Toman)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_amazing',
            field=models.BooleanField(default=False, verbose_name='is amazing?'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is available'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_best_selling',
            field=models.BooleanField(default=False, verbose_name='is best selling?'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='price (Toman)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_attributes',
            field=models.ManyToManyField(to='products.attributevalue', verbose_name='variant attributes'),
        ),
    ]
