# Generated by Django 5.2.6 on 2025-09-27 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_is_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='color name')),
                ('hex_code', models.CharField(max_length=7, verbose_name='hex code')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='fixed_attribute',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='ColorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_values', to='products.color', verbose_name='color')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='products.colorvalue', verbose_name='available colors'),
        ),
    ]
