# Generated by Django 5.2.6 on 2025-09-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='categoty',
            new_name='category',
        ),
    ]
