# Generated by Django 5.2.6 on 2025-09-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_attributevalue_is_in_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='is_in_title',
        ),
    ]
