# Generated by Django 5.2.6 on 2025-09-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_attributevalue_is_in_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.CharField(default=1, max_length=50, verbose_name='category code'),
            preserve_default=False,
        ),
    ]
