# Generated by Django 5.2.6 on 2025-09-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_options_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='parent_product',
            new_name='parent_product',
        ),
    ]
