# Generated by Django 5.2.6 on 2025-09-29 14:27

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_rename_parent_product_product_parent_name'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE products_product RENAME COLUMN parent_name_id TO parent_product_id;",
            "ALTER TABLE products_product RENAME COLUMN parent_product_id TO parent_name_id;"
        ),
    ]