# Generated by Django 5.2.6 on 2025-09-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_rename_parent_product_product_parent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='parent_name',
            new_name='parent_product',
        ),
    ]
