# Generated by Django 5.2.6 on 2025-10-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20251001_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='categories',
        ),
    ]
