# Generated by Django 5.2.6 on 2025-10-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_attributerule_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='category code')),
            ],
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ['attribute__id'], 'verbose_name': 'attribute value', 'verbose_name_plural': 'attribute values'},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_category',
            field=models.ManyToManyField(related_name='attribute_categories', to='products.attributecategory', verbose_name='related attribute categories'),
        ),
    ]
