# Generated by Django 5.2.6 on 2025-10-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_attributecategory_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_category',
        ),
        migrations.AddField(
            model_name='attributerule',
            name='attribute_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.attributecategory', verbose_name='attribute group'),
        ),
    ]
