# Generated by Django 5.2.6 on 2025-10-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_attributecategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributecategory',
            name='code',
        ),
    ]
