# Generated by Django 5.2.6 on 2025-10-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_remove_comments_product_comments_parent_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='available_colors',
            field=models.ManyToManyField(blank=True, to='products.color', verbose_name='colors'),
        ),
    ]
