# Generated by Django 5.2.6 on 2025-10-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_remove_product_color_parentproduct_available_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentproduct',
            name='available_colors',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
