# Generated by Django 5.2.6 on 2025-10-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
