# Generated by Django 5.2.6 on 2025-10-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_attribute_show_in_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_full_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Full Name (Cached)'),
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='specification_values',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attribute__show_in_specifications': True}, related_name='parent_products', to='products.attributevalue', verbose_name='shared specifications'),
        ),
    ]
