# Generated by Django 5.2.6 on 2025-11-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_alter_productimage_options_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='allow_multiple_values',
            field=models.BooleanField(default=False, verbose_name='امکان انتخاب چند مقدار همزمان در واریانت'),
        ),
    ]
