# Generated by Django 5.2.6 on 2025-11-27 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_attribute_allow_multiple_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentproduct',
            options={'ordering': ['category', 'brand', 'name'], 'verbose_name': 'parent product', 'verbose_name_plural': 'parent products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], default='amount', max_length=50, verbose_name='discount type'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.PositiveIntegerField(default=0, verbose_name='discount value'),
        ),
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True, verbose_name='final price'),
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_parents', to='products.brand', verbose_name='brand'),
            preserve_default=False,
        ),
    ]
